<a href="https://colab.research.google.com/github/MarceloEbed/dio-curso-etl/blob/main/praticandopandas2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
falsy_values = (0, False, None, '', [], {})

In [3]:
any(falsy_values)

False

In [4]:
np.nan

nan

In [5]:
3 + np.nan

nan

In [6]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])

In [7]:
a.sum()

nan

In [8]:
a.mean()

nan

In [9]:
3 + None

TypeError: ignored

In [10]:
a = np.array([1, 2, 3, np.nan, None, 4], dtype='float')

In [11]:
a

array([ 1.,  2.,  3., nan, nan,  4.])

In [12]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])

In [13]:
a.mean()

nan

In [14]:
a.sum()

nan

In [15]:
np.inf

inf

In [16]:
3 + np.inf

inf

In [17]:
np.inf / 3

inf

In [18]:
np.inf / np.inf

nan

In [19]:
b = np.array([1, 2, 3, np.inf, np.nan, 4], dtype=np.float)

In [20]:
b.sum()

nan

In [21]:
np.isnan(np.nan)

True

In [22]:
np.isinf(np.inf)

True

In [23]:
np.isfinite(np.nan), np.isfinite(np.inf)

(False, False)

In [24]:
np.isnan(np.array([1, 2, 3, np.nan, np.inf, 4]))

array([False, False, False,  True, False, False])

In [25]:
np.isinf(np.array([1, 2, 3, np.nan, np.inf, 4]))

array([False, False, False, False,  True, False])

In [26]:
np.isfinite(np.array([1, 2, 3, np.nan, np.inf, 4]))

array([ True,  True,  True, False, False,  True])

In [27]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])

In [28]:
a[~np.isnan(a)]

array([1., 2., 3., 4.])

In [29]:
a[np.isfinite(a)]

array([1., 2., 3., 4.])

In [30]:
a[np.isfinite(a)].sum()

10.0

In [31]:
a[np.isfinite(a)].mean()

2.5