<a href="https://colab.research.google.com/github/MarceloEbed/dio-curso-etl/blob/main/Usando_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Usando biblioteca numpy


In [ ]:
import sys
import numpy as np 


In [ ]:
A = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])

print(A[:, :2])

[['a' 'b']
 ['d' 'e']
 ['g' 'h']]


In [ ]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

print (B)


[[[12 11 10]
  [ 9  8  7]]

 [[ 6  5  4]
  [ 3  2  1]]]


In [ ]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [ ]:
A

array([['a', 'b', 'c'],
       ['d', 'e', 'f'],
       ['g', 'h', 'i']], dtype='<U1')

In [ ]:
A[:, :2]

array([['a', 'b'],
       ['d', 'e'],
       ['g', 'h']], dtype='<U1')

In [ ]:
B.shape

(2, 2, 3)

In [ ]:
B.ndim

3

In [ ]:
B.size

12

In [ ]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  import sys


In [ ]:
C.dtype

dtype('O')

In [ ]:
C.shape

(2,)

In [ ]:
C.size

2

In [ ]:
type(C[0])

list

**Indexando Matrizes **

In [ ]:
# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [ ]:
A[1]

array([4, 5, 6])

In [ ]:
A[1][0]

4

In [ ]:
A[1, 0]

4

In [ ]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [ ]:
A


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
A[1] = np.array([10, 10, 10])

In [ ]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [ ]:
A[2] = 99

In [ ]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

**Estatisticas**

In [ ]:
a = np.array([1, 2, 3, 4])

In [ ]:
a.sum()

10

In [ ]:
a.mean()

2.5

In [ ]:
a.std()

1.118033988749895

In [ ]:
a.var()

1.25

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [ ]:
A.sum()

45

In [ ]:
A.mean()

5.0

In [ ]:
A.std()

2.581988897471611

In [ ]:
A.sum(axis=0)

array([12, 15, 18])

In [ ]:
A.sum(axis=1)

array([ 6, 15, 24])

In [ ]:
A.mean(axis=0)

array([4., 5., 6.])

In [ ]:
A.mean(axis=1)

array([2., 5., 8.])

In [ ]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [ ]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

**Broadcasting and Vectorized operations**

In [ ]:
a = np.arange(4)

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
a + 10

array([10, 11, 12, 13])

In [ ]:
a * 10

array([ 0, 10, 20, 30])

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
a += 100

In [ ]:
a

array([100, 101, 102, 103])

In [ ]:

l = [0, 1, 2, 3]

In [ ]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [ ]:

a = np.arange(4)

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:

b = np.array([10, 10, 10, 10])

In [ ]:
b

array([10, 10, 10, 10])

In [ ]:
a + b

array([10, 11, 12, 13])

In [ ]:
a * b

array([ 0, 10, 20, 30])

**Boolean arrays**

In [ ]:
a = np.arange(4)

In [ ]:
a


array([0, 1, 2, 3])

In [ ]:
a[0], a[-1]

(0, 3)

In [ ]:
a[[0, -1]]

array([0, 3])

In [ ]:
a[[True, False, False, True]]

array([0, 3])

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
a >= 2

array([False, False,  True,  True])

In [ ]:
a[a >= 2]

array([2, 3])

In [ ]:
a.mean()

1.5

In [ ]:
a[a > a.mean()]

array([2, 3])

In [ ]:
a[~(a > a.mean())]

array([0, 1])

In [ ]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [ ]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [ ]:
A = np.random.randint(100, size=(3, 3))

In [ ]:
A

array([[96, 44, 28],
       [30, 35, 65],
       [99, 82, 91]])

In [ ]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([96, 28, 35, 99, 91])

In [ ]:
A > 30

array([[ True,  True, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [ ]:
A[A > 30]

array([96, 44, 35, 65, 99, 82, 91])

Linear Algebra

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [ ]:
A.dot(B)
A @ B
B.T
A
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

In [ ]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

In [ ]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [ ]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [ ]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [ ]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

Size of objects in Memory

In [ ]:
# Um número inteiro em Python é> 24 bytes
sys.getsizeof(1)

28

In [ ]:
# Longs são ainda maiores
sys.getsizeof(10**100)

72

In [ ]:
# O tamanho do Numpy é muito menor
np.dtype(int).itemsize

8

In [ ]:
# O tamanho do Numpy é muito menor
np.dtype(np.int8).itemsize

1

In [ ]:
np.dtype(float).itemsize

8

and performance is also important

In [ ]:
l = list(range(100000))

In [ ]:
a = np.arange(100000)

In [ ]:
%time np.sum(a ** 2)

CPU times: user 1.19 ms, sys: 800 µs, total: 1.99 ms
Wall time: 1.89 ms


333328333350000

In [ ]:
%time sum([x ** 2 for x in l])

CPU times: user 9 µs, sys: 1e+03 ns, total: 10 µs
Wall time: 15.3 µs


14

In [ ]:
np.random.random(size=2)

array([0.12463544, 0.76407285])

In [ ]:
np.random.normal(size=2)

array([1.30224354, 1.01049153])

In [ ]:
np.random.rand(2, 4)

array([[0.73597439, 0.63861682, 0.09499259, 0.13114697],
       [0.48252763, 0.02870338, 0.31972883, 0.33010372]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [ ]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((3, 3), dtype=np.int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [ ]:
"Hello World"[6]

'W'

In [ ]:
"Hello Word"


'Hello Word'

In [ ]:
"Hello Word"[3]

'l'

In [ ]:
a = np.arange(5)
a + 20

array([20, 21, 22, 23, 24])

In [ ]:
a = np.arange(5)

print(a <= 3)

[ True  True  True  True False]
